PREFIX=$1

export AWS_ACCESS_KEY_ID=$(eval "echo \$${PREFIX}_AWS_ACCESS_KEY_ID")
export AWS_SECRET_ACCESS_KEY=$(eval "echo \$${PREFIX}_AWS_SECRET_ACCESS_KEY")
export AWS_S3_BUCKET=$(eval "echo \$${PREFIX}_S3_BUCKET")
export AUTH0_DOMAIN=$(eval "echo \$${PREFIX}_AUTH0_DOMAIN")
export AUTH0_CLIENT_ID=$(eval "echo \$${PREFIX}_AUTH0_CLIENT_ID")
export AUTH0_DEPLOY_CLIENT_ID=$(eval "echo \$${PREFIX}_AUTH0_DEPLOY_CLIENT_ID")
export AUTH0_DEPLOY_CLIENT_SECRET=$(eval "echo \$${PREFIX}_AUTH0_DEPLOY_CLIENT_SECRET")
export ACCOUNTS_DOMAIN=$(eval "echo \$${PREFIX}_ACCOUNTS_DOMAIN")