version: 2
jobs:
  "build-dev":
    docker:
      - image: node:5.10.1
    steps:
      - run:
          name: Installation of build dependencies.
          command: |
            set +e
            apt-get update -y
            apt-get install g++-4.8  -y
            apt install awscli -y
            chmod 777 /etc/mime.types
            sed -i 's/^application\/x-font-woff.*/application\/font-woff\t\t\t\twoff/' /etc/mime.types
            sed -i 's/^image\/vnd.microsoft.icon.*/image\/vnd.microsoft.icon/' /etc/mime.types
            sed -i 's/^image\/x-icon.*/image\/x-icon\t\t\t\tico/' /etc/mime.types			
      - checkout
      - restore_cache:
          key: ac-node-modules-{{ checksum "package.json" }}
      - run: npm install
      - save_cache:
          key: ac-node-modules-{{ checksum "package.json" }}
          paths:
            - node_modules
      - run: npm rebuild node-sass
      - run: npm run build
      - run: npm run build-connector
      - run: npm test
      - run: ./deploy.sh DEV
  "build-qa":
    docker:
      - image: node:5.10.1
    steps:
      - run:
          name: Installation of build dependencies.
          command: |
            apt-get update -y
            apt-get install g++-4.8  -y
            apt install awscli -y            
            chmod 777 /etc/mime.types
            sed -i 's/^application\/x-font-woff.*/application\/font-woff\t\t\t\twoff/' /etc/mime.types
            sed -i 's/^image\/vnd.microsoft.icon.*/image\/vnd.microsoft.icon/' /etc/mime.types
            sed -i 's/^image\/x-icon.*/image\/x-icon\t\t\t\tico/' /etc/mime.types			
      - checkout
      - restore_cache:
          key: ac-node-modules-{{ checksum "package.json" }}
      - run: npm install
      - save_cache:
          key: ac-node-modules-{{ checksum "package.json" }}
          paths:
            - node_modules
      - run: npm run build
      - run: npm run build-connector
      - run: npm test
      - run: ./deploy.sh QA
  "build-prod":
    docker:
      - image: node:5.10.1
    steps:
      - run:
          name: Installation of build dependencies.
          command: |
            set +e
            apt-get update -y
            apt-get install g++-4.8  -y
            apt install awscli -y            
            chmod 777 /etc/mime.types
            sed -i 's/^application\/x-font-woff.*/application\/font-woff\t\t\t\twoff/' /etc/mime.types
            sed -i 's/^image\/vnd.microsoft.icon.*/image\/vnd.microsoft.icon/' /etc/mime.types
            sed -i 's/^image\/x-icon.*/image\/x-icon\t\t\t\tico/' /etc/mime.types			
      - checkout
      - restore_cache:
          key: ac-node-modules-{{ checksum "package.json" }}
      - run: npm install
      - save_cache:
          key: ac-node-modules-{{ checksum "package.json" }}
          paths:
            - node_modules
      - run: npm rebuild node-sass            
      - run: npm run build
      - run: npm run build-connector
      - run: npm test
      - run: ./deploy.sh PROD      
workflows:
  version: 2
  build:
    jobs:
      - build-dev:
          filters:
            branches:
              only: [ dev, dev-circleci2, qa-accessibility ]
      - build-qa:
          filters:
            branches:
              only: qa
      - build-prod:
          filters:
            branches:
              only: master              
